---
abstract: 'Mixin to add / call inheritable triggers'
author:
  - 'Original idea by Tony Bowden <tony@kasei.com> in Class::DBI.'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  IO::Scalar: '0'
  IO::WrapTie: '0'
  Test::More: '0.32'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.20, Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-Trigger
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  perl: '5.008001'
resources:
  bugtracker: https://github.com/miyagawa/Class-Trigger/issues
  homepage: https://github.com/miyagawa/Class-Trigger
  repository: https://github.com/miyagawa/Class-Trigger.git
version: '0.15'
x_contributors:
  - 'miyagawa <miyagawa@65690182-5df0-0310-9871-95da5a3706e7>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'tokuhirom <tokuhirom@65690182-5df0-0310-9871-95da5a3706e7>'
x_generated_by_perl: v5.20.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_static_install: 0
